import './NhsStartPage.css';

interface NhsStartPageProps {
  onStartNow: () => void;
  onBack: () => void;
  onBuildLog: () => void;
}

const ArrowIcon = () => (
  <svg className="arrow" viewBox="0 0 33 20" aria-hidden="true" focusable={false}>
    <path d="M0 8.4h25.6L19 1.8 20.8 0 30.4 9.6 20.8 19.2 19 17.4l6.6-6.6H0z" />
  </svg>
);

const TickIcon = () => (
  <svg
    className="tick"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="3"
    aria-hidden="true"
  >
    <path d="M20 6L9 17l-5-5" />
  </svg>
);

export function NhsStartPage({ onStartNow, onBack, onBuildLog }: NhsStartPageProps) {
  return (
    <div className="nhs-start-page">
      {/* QA Fix #1: Skip link — first focusable element (WCAG 2.4.1 Bypass Blocks) */}
      <a href="#main-content" className="skip-link" data-testid="nhs-skip-link">
        Skip to main content
      </a>

      {/* NHS header bar */}
      <header className="nhs-header" role="banner">
        <div className="nhs-header-inner">
          <div className="nhs-logo">
            <div className="nhs-logo-mark" aria-hidden="true">NHS</div>
            <div>
              <div className="nhs-logo-text">Patient Feedback Intelligence</div>
              <div className="nhs-logo-sub">NHS England FFT · Analytics service</div>
            </div>
          </div>
        </div>
      </header>

      {/* Back to host showcase */}
      <div className="backbar">
        <button
          className="back-link"
          onClick={onBack}
          data-testid="nhs-start-back-link"
          aria-label="Back to S&PE showcase"
        >
          <span className="chev" aria-hidden="true">‹</span>
          Back to S&amp;PE showcase
        </button>
      </div>

      {/* Main content */}
      <main id="main-content" className="page" tabIndex={-1}>
        <div className="wrap">

          {/* Service name + lead */}
          <div className="hero measure">
            <p className="svc-eyebrow">NHS analytics service</p>
            <h1>Patient Feedback Intelligence</h1>
            <p className="lead">
              Turn NHS patient feedback into prioritised, actionable insight — analysing every
              Friends and Family Test comment, not just a sample.
            </p>
          </div>

          {/* What this service does */}
          <section className="section measure prose" aria-labelledby="what-h">
            <h2 id="what-h">What this service does</h2>
            <p>
              NHS trusts receive far more patient feedback than they can read. Free-text
              comments are coded by hand from a 10–20% sample, so emerging risks surface weeks
              late — often from a complaint or the press rather than from the data. Under the 10
              Year Health Plan, patient ratings are now linked to trust income, so a missed
              signal has a direct cost.
            </p>
            <p>
              This platform reads 100% of Friends and Family Test comments and classifies each
              one against the five CQC domains — safe, effective, caring, responsive, and
              well-led. It surfaces the wards that are deteriorating fastest as prioritised
              signals, backs each one with the patients' own words, and tracks whether the
              action you take moves the score.{' '}
              <span className="ai-inline">
                <span className="ai-spark" aria-hidden="true">✦</span>
                {' '}Themes, summaries and severity are generated by AI
              </span>{' '}
              and shown with a confidence score.
            </p>
            <p>
              The result is board- and CQC-ready evidence in hours instead of weeks — and a
              feedback loop that reaches the ward, not just the boardroom.
            </p>
          </section>

          {/* Primary start button */}
          <div className="start-row measure">
            <button
              className="start-btn"
              onClick={onStartNow}
              data-testid="nhs-start-now-btn"
              aria-label="Start now — enter the dashboard"
            >
              Start now
              <ArrowIcon />
            </button>
            <button
              className="secondary-link"
              onClick={onBuildLog}
              data-testid="nhs-build-log-link"
            >
              How this was built
            </button>
          </div>

        </div>

        {/* Who it's for — tinted band */}
        <div className="band">
          <div className="wrap">
            <section className="section" aria-labelledby="who-h">
              <h2 id="who-h">Who it's for</h2>
              <p className="who-intro">
                This service is for three roles, each with its own view of the same data.
                Inside the dashboard you switch between them with the persona selector.
              </p>
              <div className="persona-grid">

                <article className="persona-card">
                  <div className="persona-num">Persona 01</div>
                  <div className="persona-role">Chief Nurse</div>
                  <div className="persona-sub">Director of Patient Experience</div>
                  <p className="persona-desc">
                    Trust-wide risk visibility at a glance, and board-ready packs exported in
                    one click — with no manual preparation.
                  </p>
                  <span className="persona-layer">
                    <span className="layer-dot" aria-hidden="true" />
                    Strategic layer
                  </span>
                </article>

                <article className="persona-card">
                  <div className="persona-num">Persona 02</div>
                  <div className="persona-role">Quality Manager</div>
                  <div className="persona-sub">Patient Experience Lead</div>
                  <p className="persona-desc">
                    Theme analysis across every comment, drilldown to patient verbatims, and
                    CQC evidence packaged for inspection.
                  </p>
                  <span className="persona-layer">
                    <span className="layer-dot" aria-hidden="true" />
                    Analytical layer
                  </span>
                </article>

                <article className="persona-card">
                  <div className="persona-num">Persona 03</div>
                  <div className="persona-role">Ward Manager</div>
                  <div className="persona-sub">Service Line Lead</div>
                  <p className="persona-desc">
                    The concerns and the positive feedback from your ward, in a form you can
                    read in three minutes on a shift.
                  </p>
                  <span className="persona-layer">
                    <span className="layer-dot" aria-hidden="true" />
                    Operational layer
                  </span>
                </article>

              </div>
            </section>
          </div>
        </div>

        {/* What's inside the dashboard */}
        <div className="wrap">
          <section className="section" aria-labelledby="inside-h">
            <h2 id="inside-h">What's inside the dashboard</h2>
            <ul className="inside-list">
              <li>
                <TickIcon />
                <strong>National FFT benchmark</strong> — how each care setting compares
                month on month
              </li>
              <li>
                <TickIcon />
                <strong>Issue tracker with prioritised signals</strong> — the top
                deteriorating wards first
              </li>
              <li>
                <TickIcon />
                <strong>Patient verbatims</strong> — representative comments behind every
                theme
              </li>
              <li>
                <TickIcon />
                <strong>Board pack export</strong> — trust-wide sentiment and risks as a PDF
              </li>
              <li>
                <TickIcon />
                <strong>CQC evidence bundle</strong> — feedback processed, themes, and
                actions logged
              </li>
            </ul>

            {/* Repeat primary action at foot of content */}
            <div className="start-again">
              <button
                className="start-btn"
                onClick={onStartNow}
                aria-label="Start now — enter the dashboard"
              >
                Start now
                <ArrowIcon />
              </button>
            </div>
          </section>
        </div>
      </main>

      {/* Demo / provenance footer */}
      <footer className="svc-footer" role="contentinfo">
        <div className="svc-footer-inner">
          <span className="demo-flag">DEMO DATA ONLY — NOT FOR CLINICAL USE</span>
          <div>
            An Accenture S&amp;PE product demo.{' '}
            <span className="ai-line">
              <span className="ai-spark" aria-hidden="true">✦</span>
              {' '}AI-assisted
            </span>{' '}
            — themes and summaries are AI-generated and reviewed before use. Data shown is
            synthetic.
          </div>
          <div className="prov">
            Patient Feedback Intelligence Platform · NHS England FFT · July 2026
          </div>
        </div>
      </footer>
    </div>
  );
}
